import type { Metadata } from "next";
import localFont from "next/font/local";
// import { SpeedInsights } from "@vercel/speed-insights/next";
// import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const poppins = localFont({
  src: [
    {
      path: "../public/fonts/poppins/Poppins-Thin.woff2",
      weight: "100",
    },
    {
      path: "../public/fonts/poppins/Poppins-ExtraLight.woff2",
      weight: "200",
    },
    {
      path: "../public/fonts/poppins/Poppins-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/poppins/Poppins-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/poppins/Poppins-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/poppins/Poppins-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/poppins/Poppins-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/poppins/Poppins-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "../public/fonts/poppins/Poppins-Black.woff2",
      weight: "900",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Contentful-App",
  description: "Generated by create next app and contentful",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable}`}>
        {children}
        {/* <SpeedInsights />
        <Analytics /> */}
      </body>
    </html>
  );
}
