import type { Metadata } from "next";
import localFont from "next/font/local";
// import { SpeedInsights } from "@vercel/speed-insights/next";
// import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const poppins = localFont({
  src: "./public/fonts/poppins/Poppins-Regular.woff2",
  variable: "--font-poppins",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Contentful-App",
  description: "Generated by create next app and contentful",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${geistMono.variable}`}>
        {children}
        {/* <SpeedInsights />
        <Analytics /> */}
      </body>
    </html>
  );
}
